version: '3.8' # ou a versão desejada do Docker Compose

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:alpine3.20
    container_name: postgres_jgarage
    environment:
      POSTGRES_USER: postgres      # Substitua pelo seu usuário
      POSTGRES_PASSWORD: Pamonha123*   # Substitua pela sua senha
      POSTGRES_DB: jgarage    # Substitua pelo nome do seu banco de dados
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
